# -*- coding: utf-8 -*-
"""[실습05]Convolution Neural Network

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCs1Fe-lUwu6omnwUaH7BH_Idlg_wRQv
"""

# Commented out IPython magic to ensure Python compatibility.
#pytorch 라이브러리 선언
import torch
import torch.nn as nn
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt
# %matplotlib inline

#1.MNIST Data Set 가져오기
mnist_train = dset.MNIST("", train = True, transform = transforms.ToTensor(), target_transform = None, donwload = True)
mnist_test = dset.MNIST("",train = False, transform = transforms.ToTensor(), target_transform = None , download = True)

# Commented out IPython magic to ensure Python compatibility.
#pytorch 라이브러리 선언
import torch
import torch.nn as nn
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt
# %matplotlib inline

#1.MNIST Data Set 가져오기
mnist_train = dset.MNIST("", train = True, transform = transforms.ToTensor(), target_transform = None, download = True)
mnist_test = dset.MNIST("",train = False, transform = transforms.ToTensor(), target_transform = None , download = True)

#2. MNIST Data Set 이미지 띄우기 및 길이
print("mnist_train길이:",len(mnist_train))
print("mnist_test 길이:",len(mnist_test))

#MNIST Data 하나에 대한 재원
image, label = mnist_train.__getitem__(0)
print("image data형태:", image.size())
print("label:",label)

#그리기
img = image.numpy()
plt.title("label:%d"%label)
plt.imshow(img[0],cmap = 'gray')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
#pytorch 라이브러리 선언
import torch
import torch.nn as nn
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt
# %matplotlib inline

#1.MNIST Data Set 가져오기
mnist_train = dset.MNIST("", train = True, transform = transforms.ToTensor(), target_transform = None, download = True)
mnist_test = dset.MNIST("",train = False, transform = transforms.ToTensor(), target_transform = None , download = True)

#Convoution 씌우기
image, label = mnist_train[0]
image = image.view(-1,image.size()[0],image.size()[1],image.size()[2]) #batch size, 채널, height, width

print(image.size())
print(label)

conv_layer = nn.Conv2d(in_channels = 1, out_channels=3, kernel_size = 3, padding=1)
output = conv_layer(image)
print(output.size())

for i in range(3):
  plt.imshow(output[0,i,:,:].data.numpy(), cmap = 'gray')
  plt.show()

# Commented out IPython magic to ensure Python compatibility.
#pytorch 라이브러리 선언
import torch
import torch.nn as nn
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt
# %matplotlib inline

#1.MNIST Data Set 가져오기
mnist_train = dset.MNIST("", train = True, transform = transforms.ToTensor(), target_transform = None, download = True)
mnist_test = dset.MNIST("",train = False, transform = transforms.ToTensor(), target_transform = None , download = True)

#Convoution 씌우기
image, label = mnist_train[0]
image = image.view(-1,image.size()[0],image.size()[1],image.size()[2]) #batch size, 채널, height, width

print(image.size())
print(label)

conv_layer = nn.Conv2d(in_channels = 1, out_channels=3, kernel_size = 3, padding=1)
output = conv_layer(image)
print(output.size())
#CNN 만들기
import numpy as np
import torch.optim as optim

batch_size = 16
learning_rate = 0.0002
num_epoch = 10

train_loader = torch.utils.data.DataLoader(list(mnist_train)[:batch_size*100],batch_size = batch_size, shuffle = True, num_workers=2)
test_loader = torch.utils.data.DataLoader((mnist_test), batch_size = batch_size, shuffle = False, num_workers=2, drop_last = True)

class CNN(nn.Module):
  def __init__(self):
    super(CNN,self).__init__()
    self.layer = nn.Sequential(
        nn.Conv2d(1,16,5,padding=2), #제 1구간
        nn.ReLU(), #제 1구간

        nn.Conv2d(16,32,5,padding=2), #제 2구간
        nn.ReLU(),
        nn.MaxPool2d(2,2), #풀링

        nn.Conv2d(32,64,5, padding=2),
        nn.ReLU(),
        nn.MaxPool2d(2,2)

    )
    self.fc_layer = nn.Sequential(
        nn.Linear(64*7*7,100),
        nn.ReLU(),
        nn.Linear(100,10)
    )

    def forward(self,x):
      out = self.layer(x)
      out = out.view(batch_size,-1)
      out = self.fc_layer(out)
      return out

model = CNN()

#Parameter Check
for parameter in model.parameters():
  print(parameter.shape)

# Commented out IPython magic to ensure Python compatibility.
#pytorch 라이브러리 선언
import torch
import torch.nn as nn
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt
# %matplotlib inline

#1.MNIST Data Set 가져오기
mnist_train = dset.MNIST("", train = True, transform = transforms.ToTensor(), target_transform = None, download = True)
mnist_test = dset.MNIST("",train = False, transform = transforms.ToTensor(), target_transform = None , download = True)

#Convoution 씌우기
image, label = mnist_train[0]
image = image.view(-1,image.size()[0],image.size()[1],image.size()[2]) #batch size, 채널, height, width

print(image.size())
print(label)

conv_layer = nn.Conv2d(in_channels = 1, out_channels=3, kernel_size = 3, padding=1)
output = conv_layer(image)
print(output.size())
#CNN 만들기
import numpy as np
import torch.optim as optim

batch_size = 16
learning_rate = 0.0002
num_epoch = 10

train_loader = torch.utils.data.DataLoader(list(mnist_train)[:batch_size*100],batch_size = batch_size, shuffle = True, num_workers=2)
test_loader = torch.utils.data.DataLoader((mnist_test), batch_size = batch_size, shuffle = False, num_workers=2, drop_last = True)

class CNN(nn.Module):
  def __init__(self):
    super(CNN,self).__init__()
    self.layer = nn.Sequential(
        nn.Conv2d(1,16,5,padding=2), #제 1구간
        nn.ReLU(), #제 1구간

        nn.Conv2d(16,32,5,padding=2), #제 2구간
        nn.ReLU(),
        nn.MaxPool2d(2,2), #풀링

        nn.Conv2d(32,64,5, padding=2),
        nn.ReLU(),
        nn.MaxPool2d(2,2)

    )
    self.fc_layer = nn.Sequential(
        nn.Linear(64*7*7,100),
        nn.ReLU(),
        nn.Linear(100,10)
    )

    def forward(self,x):
      out = self.layer(x)
      out = out.view(batch_size,-1)
      out = self.fc_layer(out)
      return out

model = CNN()

#Parameter Check
#for parameter in model.parameters():
  #print(parameter.shape)

#Optimized
loss_func = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

for i in range(num_epoch):
  for j,[image,label] in enumerate(train_loader):
    x = Variable(image)
    y_ = Variable(label)

    optimizer.zero_grad()
    output = model.forward(x)
    loss = loss_func(output, y_)
    loss.backward()
    optimizer.step()

    if j%50 == 0:
      print(loss,j,i)

# Commented out IPython magic to ensure Python compatibility.
#pytorch 라이브러리 선언
import torch
import torch.nn as nn
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt
# %matplotlib inline

#1.MNIST Data Set 가져오기
mnist_train = dset.MNIST("", train = True, transform = transforms.ToTensor(), target_transform = None, download = True)
mnist_test = dset.MNIST("",train = False, transform = transforms.ToTensor(), target_transform = None , download = True)

#Convoution 씌우기
image, label = mnist_train[0]
image = image.view(-1,image.size()[0],image.size()[1],image.size()[2]) #batch size, 채널, height, width

print(image.size())
print(label)

conv_layer = nn.Conv2d(in_channels = 1, out_channels=3, kernel_size = 3, padding=1)
output = conv_layer(image)
print(output.size())
#CNN 만들기
import numpy as np
import torch.optim as optim

batch_size = 16
learning_rate = 0.0002
num_epoch = 10

train_loader = torch.utils.data.DataLoader(list(mnist_train)[:batch_size*100],batch_size = batch_size, shuffle = True, num_workers=2)
test_loader = torch.utils.data.DataLoader((mnist_test), batch_size = batch_size, shuffle = False, num_workers=2, drop_last = True)

class CNN(nn.Module):
  def __init__(self):
    super(CNN,self).__init__()
    self.layer = nn.Sequential(
        nn.Conv2d(1,16,5,padding=2), #제 1구간
        nn.ReLU(), #제 1구간

        nn.Conv2d(16,32,5,padding=2), #제 2구간
        nn.ReLU(),
        nn.MaxPool2d(2,2), #풀링

        nn.Conv2d(32,64,5, padding=2),
        nn.ReLU(),
        nn.MaxPool2d(2,2)

    )
    self.fc_layer = nn.Sequential(
        nn.Linear(64*7*7,100),
        nn.ReLU(),
        nn.Linear(100,10)
    )

  def forward(self,x):
    out = self.layer(x)
    out = out.view(batch_size,-1)
    out = self.fc_layer(out)
    return out

model = CNN()

#Parameter Check
for parameter in model.parameters():
  print(parameter.shape)

#Checking Performance

def ComputerAccr(dloader, imodel):
  correct = 0
  total = 0

  for j,[imgs, labels] in enumerate(dloader):
    img = Variable(imgs)
    label = Variable(labels)

    output = imodel.forward(img)
    _, output_index = torch.max(output,1)

    total += label.size(0)
    correct += (output_index == label).sum().float()

  print("Accuracy of Test Data:{}".format(100*correct/total))
ComputerAccr(test_loader, model)

