# -*- coding: utf-8 -*-
"""[DL][04]Deep Learning Training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kr9zHG_oGjEFT5BnFsICQ_uvhr3UKunj
"""

#1. 라이브러리 선언
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import torchvision.dataset as dset
import torchvision.transforms as transforms
from torch.utils,data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt

#Learning rate decay
from torch.optim import lr_scheduler

batch_size = 16 #Hyper Parameter
learning_rate = 0.002 #Hyper Parameter
num_epoch = 1  #Hypter Parameter

#1. CIFAR10 train, test dataset 가져오기 (163MB)
cifar_train = dset.CIFAR10("CIFAR10/", train = True, transform=transforms.ToTensor(),target_transform = None, download = True)
cifar_test = dset.CIFAR10("CIFAR10/", train = False, transform = transforms.ToTensor(), target_transform = None , download = True)

#모델 성능 측정
def CompterAcc(dloader, imodel):
  correct = 0
  total = 0

  for j,[imgs,labels] in enumerate(dloader):
    img = Variable(imgs, volatile=True)
    label = Variable(labels)

    output = imodel.forward(img)
    _, output_index = torch.max(output, 1)

    total += label.size(0)
    correct += (output_inde == label).sum().float()

  print("Accuracy of Test Data: {}".format(100*correct/total))

#3. 데이터 로드 함수
train_loader = torch.utils.data.DataLoader(list(cifar_train)[:],batch_size = batch_size,shuffle = True, num_workers=2, drop_last = True)
test_loader = torch.utils.data.DatLoader(cifar_test, batch_size = batch_size, shuffle=False, num_workers=2, drop_last = True)

#4. 모델 선언
class CNN(nn.Module):
  def __init__(self):
    super(CNN,self).__init__()
    self.layer = nn.Sequential(
        nn.Conv2d(3,16,3,padding=1),
        nn.ReLU(),
        #nn.Dropout2d(0,2), #DropOut
        #nn.BatchNorm2d(16), #배치 정규화
        nn.Conv2d(16,32,3,padding =1),
        nn.ReLU(),
        #nn.Dropout2d(0,2),
        #nn.BatchNorm2d(32),
        nn.MaxPool2d(2,2),
        nn.Conv2d(32,64,3,padding =1),
        nn.ReLU(),
        #nn.Dropout2d(0,2),
        #nn.BatchNorm2d(64),
        nn.MaxPool2d(2,2)

    )

    self.fc_layer = nn.Sequential(
        nn.Linear(64*8*8,100),
        nn.ReLU(),
        #nn.Dropout2d(0,2),
        #nn.BatchNorm2d(100),
        nn.Linear(100,10)
    )

    def forward(self,x):
      out = self.layer(x)
      out = out.view(batch_size, -1)
      out = self.fc_layer(out)

      return out

model = CNN()

#5. loss , optimizer
loss_func = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate) #stochastic Gradient Descendant optimizer 사용

#6. 학습
for i in range(num_epoch):
  for j,[image,label] in enumerate(train_loader):
    x = Variable(image)
    y = Varialbe(label)

    optimizer.zero_grad()
    output = model.forward(x)
    lostt = loss_func(output,y_)
    loss.backward()
    optimizer.step()

    if j%1000 == 0:
      print(j,loss)

#전체 코드
#라이브러리 선언
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.autograd import Variable
import matplotlib.pyplot as plt

#Learning rate decay
from torch.optim import lr_scheduler

batch_size = 16 #Hyper Parameter
learning_rate = 0.002 #Hyper Parameter
num_epoch = 1  #Hypter Parameter



#1. CIFAR10 train, test dataset 가져오기 (163MB)
cifar_train = dset.CIFAR10("CIFAR10/", train = True, transform=transforms.ToTensor(),target_transform = None, download = True)
cifar_test = dset.CIFAR10("CIFAR10/", train = False, transform = transforms.ToTensor(), target_transform = None , download = True)



#3. 데이터 로드 함수
train_loader = torch.utils.data.DataLoader(list(cifar_train)[:],batch_size = batch_size,shuffle = True, num_workers=2, drop_last = True)
test_loader = torch.utils.data.DataLoader(cifar_test, batch_size = batch_size, shuffle=False, num_workers=2, drop_last = True)


#4. 모델 선언
class CNN(nn.Module):
  def __init__(self):
    super(CNN,self).__init__()
    self.layer = nn.Sequential(
        nn.Conv2d(3,16,3,padding=1),
        nn.ReLU(),
        #nn.Dropout2d(0.2), #DropOut
        #nn.BatchNorm2d(16), #배치 정규화
        nn.Conv2d(16,32,3,padding =1),
        nn.ReLU(),
        #nn.Dropout2d(0.2),
        #nn.BatchNorm2d(32),
        nn.MaxPool2d(2,2),
        nn.Conv2d(32,64,3,padding =1),
        nn.ReLU(),
        #nn.Dropout2d(0.2),
        #nn.BatchNorm2d(64),
        nn.MaxPool2d(2,2)

    )

    self.fc_layer = nn.Sequential(
        nn.Linear(64*8*8,100),
        nn.ReLU(),
        #nn.Dropout2d(0,2),
        #nn.BatchNorm2d(100),
        nn.Linear(100,10)
    )

    def forward(self,x):
      out = self.layer(x)
      out = out.view(batch_size, -1)
      out = self.fc_layer(out)

      return out

model = CNN()


#5. loss , optimizer
loss_func = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate) #stochastic Gradient Descendant optimizer 사용


#6. 학습
for i in range(num_epoch):
  for j,[image,label] in enumerate(train_loader):
    x = Variable(image)
    y = Variable(label)

    optimizer.zero_grad()
    output = model.forward(x)
    loss = loss_func(output,y)
    loss.backward()
    optimizer.step()

    if j%1000 == 0:
      print(j,loss)
